import {
  DarkElf,
  Dragonborn,
  HalfOrc,
  HighElf,
  HillDwarf,
  MountainDwarf,
  WoodElf,
  AirGenasi,
  EarthGenasi,
  WaterGenasi,
  FireGenasi,
  MountainGnome,
  ForestGnome,
  HalfElf,
  Lightfoot,
  Stout,
  BaseHuman,
  Barbarian,
  Criminal,
  VariantHuman,
  Tiefling,
  Artificer,
  Bard,
  Cleric,
  Druid,
  Fighter,
  Monk,
  Paladin,
  Ranger,
  Rogue,
  Sorcerer,
  Warlock,
  Wizard,
  Acolyte,
  Charlatan,
  Entertainer,
  FolkHero,
  GuildArtisan,
  Hermit,
  Knight,
  Noble,
  Outlander,
  Pirate,
  Sage,
  Sailor,
  Soldier,
  Urchin,
} from "../index";

export const raceDict = {
    "Dragonborn": Dragonborn,
    "Hill Dwarf": HillDwarf,
    "Mountain Dwarf": MountainDwarf,
    "Dark Elf": DarkElf,
    "High Elf": HighElf,
    "Wood Elf": WoodElf,
    "Air Genasi": AirGenasi,
    "Earth Genasi": EarthGenasi,
    "Fire Genasi": FireGenasi,
    "Water Genasi": WaterGenasi,
    "Forest Gnome": ForestGnome,
    "Mountain Gnome": MountainGnome,
    "Half Elf": HalfElf,
    "Half Orc": HalfOrc,
    "Lightfoot Halfling": Lightfoot,
    "Stout Halfling": Stout,
    "Base Human": BaseHuman,
    "Variant Human": VariantHuman,
    "Tiefling": Tiefling,
};

export const classDict = {
    "Artificer": Artificer,
    "Barbarian": Barbarian,
    "Bard": Bard,
    "Cleric": Cleric,
    "Druid": Druid,
    "Fighter": Fighter, 
    "Monk": Monk,
    "Paladin": Paladin,
    "Ranger": Ranger, 
    "Rogue": Rogue,
    "Sorcerer": Sorcerer,
    "Warlock": Warlock, 
    "Wizard": Wizard
};

export const bgDict = {
    "Acolyte": Acolyte, 
    "Charlatan": Charlatan,
    "Criminal": Criminal,
    "Entertainer": Entertainer,
    "Folk Hero": FolkHero,
    "Guild Artisan": GuildArtisan, 
    "Hermit": Hermit,
    "Knight": Knight,
    "Noble": Noble,
    "Outlander": Outlander,
    "Pirate": Pirate,
    "Sage": Sage,
    "Sailor": Sailor,
    "Soldier": Soldier,
    "Urchin": Urchin
};
