import {
  DarkElf,
  Dragonborn,
  HalfOrc,
  HighElf,
  HillDwarf,
  MountainDwarf,
  WoodElf,
  AirGenasi,
  EarthGenasi,
  WaterGenasi,
  FireGenasi,
  MountainGnome,
  ForestGnome,
  HalfElf,
  Lightfoot,
  Stout,
  BaseHuman,
  Barbarian,
  Criminal,
  VariantHuman,
  Tiefling,
  Artificer,
  Bard,
  Cleric,
  Druid,
  Fighter,
  Monk,
  Paladin,
  Ranger,
  Rogue,
  Sorcerer,
  Warlock,
  Wizard,
  Acolyte,
  Charlatan,
  Entertainer,
  FolkHero,
  GuildArtisan,
  Hermit,
  Knight,
  Noble,
  Outlander,
  Pirate,
  Sage,
  Sailor,
  Soldier,
  Urchin,
  Actor,
  Alert,
  Athlete,
  Charger,
  CrossbowExpert,
  DefensiveDuelist,
  DualWielder,
  DungeonDelver,
  Durable,
  ElementalAdept,
  Grappler,
  GreatWeaponMaster,
  Healer,
  HeavilyArmored,
  HeavyArmorMaster,
  InspiringLeader,
  KeenMind,
  LightlyArmored,
  Linguist,
  Lucky,
  MageSlayer,
  MagicInitiate,
  MartialAdept,
  MediumArmorMaster,
  Mobile,
  ModeratelyArmored,
  MountedCombatant,
  Observant,
  PolearmMaster,
  Resilient,
  RitualCaster,
  SavageAttacker,
  Sentinel,
  Sharpshooter,
  ShieldMaster,
  Skilled,
  Skulker,
  SpellSniper,
  TavernBrawler,
  Tough,
  WarCaster,
  WeaponMaster,
} from "../index";

export const raceDict = {
  Dragonborn: Dragonborn,
  "Hill Dwarf": HillDwarf,
  "Mountain Dwarf": MountainDwarf,
  "Dark Elf": DarkElf,
  "High Elf": HighElf,
  "Wood Elf": WoodElf,
  "Air Genasi": AirGenasi,
  "Earth Genasi": EarthGenasi,
  "Fire Genasi": FireGenasi,
  "Water Genasi": WaterGenasi,
  "Forest Gnome": ForestGnome,
  "Mountain Gnome": MountainGnome,
  "Half Elf": HalfElf,
  "Half Orc": HalfOrc,
  "Lightfoot Halfling": Lightfoot,
  "Stout Halfling": Stout,
  "Base Human": BaseHuman,
  "Variant Human": VariantHuman,
  Tiefling: Tiefling,
};

export const classDict = {
  Artificer: Artificer,
  Barbarian: Barbarian,
  Bard: Bard,
  Cleric: Cleric,
  Druid: Druid,
  Fighter: Fighter,
  Monk: Monk,
  Paladin: Paladin,
  Ranger: Ranger,
  Rogue: Rogue,
  Sorcerer: Sorcerer,
  Warlock: Warlock,
  Wizard: Wizard,
};

export const bgDict = {
  Acolyte: Acolyte,
  Charlatan: Charlatan,
  Criminal: Criminal,
  Entertainer: Entertainer,
  "Folk Hero": FolkHero,
  "Guild Artisan": GuildArtisan,
  Hermit: Hermit,
  Knight: Knight,
  Noble: Noble,
  Outlander: Outlander,
  Pirate: Pirate,
  Sage: Sage,
  Sailor: Sailor,
  Soldier: Soldier,
  Urchin: Urchin,
};

export const featDict = {
  Actor: Actor,
  Alert: Alert,
  Athlete: Athlete,
  Charger: Charger,
  "Crossbow Expert": CrossbowExpert,
  "Defensive Duelist": DefensiveDuelist,
  "Dual Wielder": DualWielder,
  "Dungeon Delver": DungeonDelver,
  Durable: Durable,
  "Elemental Adept": ElementalAdept,
  Grappler: Grappler,
  "Great Weapon Master": GreatWeaponMaster,
  Healer: Healer,
  "Heavily Armored": HeavilyArmored,
  "Heavy Armor Master": HeavyArmorMaster,
  "Inspiring Leader": InspiringLeader,
  "Keen Mind": KeenMind,
  "Lightly Armored": LightlyArmored,
  Linguist: Linguist,
  Lucky: Lucky,
  "Mage Slayer": MageSlayer,
  "Magic Initiate": MagicInitiate,
  "Martial Adept": MartialAdept,
  "Medium Armor Master": MediumArmorMaster,
  Mobile: Mobile,
  "Moderately Armored": ModeratelyArmored,
  "Mounted Combatant": MountedCombatant,
  Observant: Observant,
  "Polearm Master": PolearmMaster,
  Resilient: Resilient,
  "Ritual Caster": RitualCaster,
  "Savage Attacker": SavageAttacker,
  Sentinel: Sentinel,
  Sharpshooter: Sharpshooter,
  "Shield Master": ShieldMaster,
  Skilled: Skilled,
  Skulker: Skulker,
  "Spell Sniper": SpellSniper,
  "Tavern Brawler": TavernBrawler,
  Tough: Tough,
  "War Caster": WarCaster,
  "Weapon Master": WeaponMaster,
};
